
      - name: Deploy files to EC2

        shell: pwsh

        run: |

          $scpExe = "C:\Program Files\Git\usr\bin\scp.exe"

          & $scpExe -i "$env:USERPROFILE\.ssh\id_rsa" -o StrictHostKeyChecking=no deploy-bundle.zip ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ env.REMOTE_DEPLOY_PATH }}



      - name: Execute remote commands on EC2

        uses: appleboy/ssh-action@v1.0.3

        with:

          host: ${{ secrets.SSH_HOST }}

          username: ${{ secrets.SSH_USERNAME }}

          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |

            cd ${{ env.REMOTE_DEPLOY_PATH }}

            unzip -o deploy-bundle.zip
