name: Deploy to Windows EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download WinSCP Portable
        run: |
          Invoke-WebRequest -Uri "https://winscp.net/download/WinSCP-5.21.5-Portable.zip" -OutFile "WinSCP.zip"
          Expand-Archive -Path "WinSCP.zip" -DestinationPath "WinSCP"

      - name: Deploy files to EC2 via WinSCP
        run: |
          .\WinSCP\WinSCP.com /command `
            "open sftp://msq9831:Rawalpindi!23@3.86.53.225/" `
            "put ./publish/* /C:/inetpub/wwwroot/app/" `
            "exit"
